name: Cypress Tests
on:
  push:
    branches: [ main, dev, test ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{ steps.deployment.outputs.url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Vercel Preview Deployment
        if: github.event_name == 'pull_request'
        id: deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 300000 # 5 minutes

      - name: Set production URL for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "CYPRESS_BASE_URL=https://your-production-domain.vercel.app" >> $GITHUB_ENV

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          start: npm run dev # Only needed if testing locally
          wait-on: ${{ env.CYPRESS_BASE_URL }}
          wait-on-timeout: 120
        env:
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
